Task 1: You are given the following array:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Your task is to replace each odd number with a value of -10 using only a single line of Python code. If done correctly your array should appear as follows:

array([ 0, -10,  2, -10,  4, -10,  6, -10,  8, -10])

In [11]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
arr[arr%2!=0]=-10
arr

array([  0, -10,   2, -10,   4, -10,   6, -10,   8, -10])

Task 2: You are given the following array:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Your task is to convert that 1-dimensional array to a 2-dimensional array containing 2 rows using only a single line of Python code.  If done correctly your array should appear as follows:

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])


In [13]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Task 3: You are given the following array:

arr = np.array([3,1, 6, 17, 8, 42, 10, 39, 25, 12, 14,42])

Your task is to extract all items from that array that fall between 5 and 12 (inclusive) using only a single line of Python code .  If done correctly your array should appear as follows:

array([6, 8, 10, 12])

In [17]:
# This for all the people who got confused use the amersand & , dont use 'and'
arr = np.array([3,1, 6, 17, 8, 42, 10, 39, 25, 12, 14,42])
# there you go : = D
arr[(arr > 5) & (arr < 12)]

array([ 6,  8, 10])

Task 4: You are given the following array:

arr = np.arange(9).reshape(3,3)

Your task is to swap the first and second rows of that array using only a single line of Python code.  If done correctly your array should appear as follows:

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [29]:
arr = np.arange(9).reshape(3,3)
print(arr) # 3x3 matrix
#replace 0th row with the 1st row while including all the cols
arr[[0,1],:]=arr[[1,0],:]
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [30]:
# we can also do this
arr = np.arange(9).reshape(3,3)
print(arr) # 3x3 matrix
#replace 0th row with the 1st row while including all the cols
arr[[0,1]]=arr[[1,0]]
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [31]:
# I have a question for everyone else :=) , is there named function that can help instead of this :D