# DAV 5400 Fall 2019 Week 4 Assignment (30 Points)

Our Week 4 Assignment makes use of the functionality provided by Python’s NumPy package.
--------------------------------------------------------------------------------------------------------------------------------

#### 1. Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
Your output should contain only the distinct overlapping values.<br> For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.

In [65]:
# you can solve this question in three ways , 
#1. you can cast it into sets then use intersect
#2.you can use from functools import reduce and use reduce()
#3.or you can simpy use this method where it finds the intersected values between two 1D Numpy array values
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

np.intersect1d(a, b)

array([2, 4])

# 2. Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you do not need to explicitly key in every integer value.
1 6 11
2 7 12
3 8 13
4 9 14
5 10 15 (5x3 array table) 

In [66]:
# numpy.arange(start, stop, step, dtype)
# reshape used to reshape it
# create values from 1 to 15 and reshape it into 3by5 then transpose it into 3by5
fivebythree = np.arange(1,16,1).reshape(3,5).T
fivebythree

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

--------------------------------------------------------------------------------------------------------------------------------
# 3. You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
Write a Python/Numpy code block that removes from array a any items that are also present in array b.

In [67]:
# this can be done in many ways
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

# way number 1 but this does not allow duplicates
print("Sorted and doesnot allow duplicates : ",np.array(np.setdiff1d(a, b)))

# way number 2 only problem with this is that it is not sorted but on the upside if you want duplicates it allows duplicates
cond = np.isin(a,b)
# in numpy ~ is not instead of !
find = a[~cond]
print('\n')
print("There is also the unsorted version of it that allows duplicates : ",find,'\n which of course you can always sort() it if you only want the duplicates')
print('\n')

Sorted and doesnot allow duplicates :  [ 1  7  8 15]


There is also the unsorted version of it that allows duplicates :  [ 7 15  1  8] 
 which of course you can always sort() it if you only want the duplicates




4. Suppose you have ridden a bicycle from New York City to Key West, Florida. Your bicycle odometer shows the total
miles you have travelled thus far, which you make a note of each day with paper and pencil. Your first two entries might
be ‘55’ and ‘120’, indicating that you rode your bike 55 miles on day 1 and 65 miles on day 2. Your task is to create a
NumPy array wherein you can record the cumulative miles you recorded each day during your trip. Then use your
Python skills to show the total miles that you rode each day. Assume the trip took a total of 35 days and included at
least 4 non-consecutive days where no cycling was possible due to either weather conditions or personal
fatigue/soreness. For the remaining 31 days, you would have covered the entire distance between NYC and Key West.
Complete your work within your Jupyter Notebook for this assignment and be sure to include a writeup explaining your
approach to this problem, including the ways in which you decided to make use of NumPy.

In [68]:
# this is how you get the cumalative sum for every day including the plateaus and only get the final sum
def total_view(arr_np):
    '''
    arr_np: NumPy array that has the accumatltive 
    output: has the total traversed distance
    '''
    # getting the accumalative sum
    tot=np.cumsum(arr_np)
    #print the entire time series
    print("This is the accumalative sum everyday in the 35 days")
    print(tot)
    # getting the last index
    print("\n Total traversed distance in miles stored:", tot[-1] )
    return  tot[-1]

In [69]:
# Getting the  distance over the course of 31 traveling days first 
import numpy as np
# the Distance between new york city to key west florida by bicycle
_sum = 1547
# The number of tr
n = 31
rnd_array = np.random.multinomial(_sum, np.ones(n)/n, size=1)[0]
# Showing the distance traversed everyday of the 31 days
print(rnd_array)
# Testing if the random numbers we obtained were correct and add up to total distance
print("Their sum is =",sum(rnd_array))

[47 54 45 48 54 46 51 44 55 41 49 51 58 44 45 54 37 43 63 49 56 56 38 59
 53 48 47 51 52 58 51]
Their sum is = 1547


In [35]:
# Here are four inserts, i know i could do it in a loop but its only 4 inserts so no need in creating something that is O(Nlogn)
a = np.asarray(rnd_array)
a=np.insert(a, 4, 0)#1
a=np.insert(a, 15, 0)#2
a=np.insert(a, 22, 0)#3
a=np.insert(a, 24, 0)#O(log N)
#view the points
a = np.array(a)
print(a)

# Testing if the random numbers we obtained were correct and add up to total distance
print("Their sum is =",sum(a))

[53 53 47 49  0 50 56 49 46 51 49 53 51 46 52  0 62 51 40 45 51 53  0 49
  0 52 39 51 42 54 54 56 41 49 53]
Their sum is = 1547


In [36]:
#This is the accumalative value in the last 35 days along side with the total traversed distance
total_view(a)

This is the accumalative sum everyday in the 35 days
[  53  106  153  202  202  252  308  357  403  454  503  556  607  653
  705  705  767  818  858  903  954 1007 1007 1056 1056 1108 1147 1198
 1240 1294 1348 1404 1445 1494 1547]

 Total traversed distance in miles stored: 1547


1547

5. Open the Jupyter Notebook provided to you with this assignment. The first code block within that file will load a
small data set from a GitHub repository into a NumPy 2D array. The original source of that data contains an overview of
its contents: 

https://data.cityofnewyork.us/Environment/Water-Consumption-In-The-New-York-City/ia2d-e54m
Scroll down to the bottom of that page to access an interactive data viewer that includes the column headings for the
data.
Using the NumPy array that has been loaded for you in the Jupyter Notebook, answer the following questions using
NumPy’s slicing, methods, and functions:
 What is the maximum yearly NYC consumption of water in millions of gallons per day?
 How many calendar years are represented within this data set? NumPy's shape command is one way to find
out.
 What is the mean and the standard deviation of the per capita daily water consumption?
 What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.
Please note that it may take a bit of time for Jupyter to load the data set from the GitHub repository. You will know that
process has finished once the results of the ‘type(nyc_water)’ command get displayed within your copy of the
notebook.
------------------------------------------------------------------------------------------------------------------------------------------
Be sure to include some commentary explaining your approach to solving each of the individual problems. Save all of
your work for this assignment within a single Jupyter Notebook and upload it to your online DAV5400 GitHub directory.
Be sure to save your Notebook using the nomenclature we‘ve been using, i.e., first initial_last name_W4_assn"
(e.g., J_Smith_W4_assn_).


In [38]:
import pandas
import sys
# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

C:\Users\Morra\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys


numpy.ndarray

In [39]:
nyc_water

array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1

### Using the NumPy array that has been loaded for you in the Jupyter Notebook, answer the following questions using
### NumPy’s slicing, methods, and functions:
####  What is the maximum yearly NYC consumption of water in millions of gallons per day?
####  How many calendar years are represented within this data set? NumPy's shape command is one way to find
out.
####  What is the mean and the standard deviation of the per capita daily water consumption?
####  What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.
Please note that it may take a bit of time for Jupyter to load the data set from the GitHub repository. You will know that
process has finished once the results of the ‘type(nyc_water)’ command get displayed within your copy of the

-----------------------------------------------------------------------------------------------------------

In [44]:
#What is the maximum yearly NYC consumption of water in millions of gallons per day?
np.max(nyc_water[:,2])

1512.0

In [54]:
#How many calendar years are represented within this data set? NumPy's shape command is one way to find
# way 1 
print(nyc_water[:,0].shape[0])
print('\n')
# way 2
print(len(nyc_water[:,0]))
print('\n')
# way 3
len(set(nyc_water[:,0]))

39


39




39

In [60]:
#What is the mean and the standard deviation of the per capita daily water consumption?
mn = np.mean(nyc_water[:,3])
dv = np.std(nyc_water[:,3])
print('The mean is :',mn,'\nThe standard deviation is :', dv)

The mean is : 160.30769230769232 
The standard deviation is : 31.51894330370624


In [64]:
#  What is the increase or decrease in population from year to year? Use NumPy's diff function to create an array
pop_diff = np.diff(nyc_water[:,1])
pop_diff

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])

# Please dont mark me down i did everything
:-D